SilkDjango/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings


# TODO Добавить переменные из settings в templates
"""

"""


from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    # Core
    url(r'^$', 'core.views.landing', name='home'),
    url(r'^#tf-about$', 'core.views.landing', name='about'),
    url(r'^#tf-catalog$', 'core.views.landing', name='catalog'),
    url(r'^#tf-care$', 'core.views.landing', name='care'),
    url(r'^#tf-delivery$', 'core.views.landing', name='delivery'),
    url(r'^#tf-reviews$$', 'core.views.landing', name='reviews'),
    url(r'^#tf-contact$$', 'core.views.landing', name='contact'),

    url(r'^shop/', include('shop.urls', namespace='shop')),

    # SKV
    url(r'^skv/$', 'skv.views.index', name='skv'),
    url(r'^skv/', include('skv.urls', namespace='skv')),
    )

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

if settings.DEV:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

skv/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.generic import TemplateView



urlpatterns = patterns('skv.views',
    url(r'^/$', 'index', name='index'),
    url(r'^demo/$', 'demo', name='demo'),
    url(r'^contacts/$', 'contacts', name='contacts'),

    url(r'^spirit8/original$', TemplateView.as_view(template_name='demo/spirit8.html'), name='spirit8'),

    # AJAX
    url(r'^ajax/$', TemplateView.as_view(template_name='skv/ajax_test.html'), name='ajax'),
    url(r'^ajax/test$', 'ajax_test', name='ajax_test'),
    
    # Old silk demo
    url(r'^silk/$', 'silk_old_demo_index', name='silk_index'),
    url(r'^silk/about/$', 'silk_old_demo_about', name='silk_about'),
    url(r'^silk/care/$', 'silk_old_demo_care', name='silk_care'),
    url(r'^silk/delivery/$', 'silk_old_demo_delivery', name='silk_delivery'),
    url(r'^silk/contacts/$', 'silk_old_demo_contacts', name='silk_contacts'),
)

skv/models.py
from django.db import models

# Create your models here.

skv/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse

from .form import MailForm, CallForm, ReviewForm
# Create your views here.

def index(request):
    context = {}
    return render(request, 'skv/index.html', context)

def demo(request):
    context = {}
    return render(request, 'skv/demo.html', context)

def contacts(request):
    mail_form = MailForm(prefix='mail')
    call_form = CallForm(prefix='call')
    mail_form_errors = None
    call_form_errors = None

    if request.method == 'POST' and 'mail' in request.POST:
        mail_form = MailForm(request.POST, prefix='mail')
        if mail_form.is_valid():
            messages.success(request, "Mail Form Success!")
            return redirect('skv:contacts')
        else:
            messages.error(request, 'Mail Form Error')

    if request.method == 'POST' and 'call' in request.POST:
        call_form = CallForm(request.POST, prefix='call')
        if call_form.is_valid():
            messages.success(request, "Call Form Success!")
            return redirect('skv:contacts')
        else:
            print(call_form.errors)
            messages.error(request, 'Call Form Error')

    context = {'mail_form': mail_form,
               'call_form': call_form,
               'mail_form_errors': mail_form_errors,
               'call_form_errors': call_form_errors,
               }
    return render(request, 'skv/contacts.html', context)

#
# Ajax test
#

def ajax_test(request):
    pass
    return HttpResponse('Test AJAX')

#
#
#
# Old silk demo
#
#
#

def silk_old_demo_index(request):
    context = {'msg': 'Hello Amigo!'
               }
    return render(request, 'silk/index.html', context)

def silk_old_demo_about(request):
    context = {'msg': 'Hello Amigo!'
               }
    return render(request, 'silk/about.html', context)

def silk_old_demo_care(request):
    context = {'msg': 'Hello Amigo!'
               }
    return render(request, 'silk/care.html', context)

def silk_old_demo_delivery(request):
    context = {'msg': 'Hello Amigo!'
               }
    return render(request, 'silk/delivery.html', context)

def silk_old_demo_contacts(request):
    mail_form = MailForm(prefix='mail')
    call_form = CallForm(prefix='call')
    mail_form_errors = None
    call_form_errors = None

    if request.method == 'POST' and 'mail' in request.POST:
        mail_form = MailForm(request.POST, prefix='mail')
        if mail_form.is_valid():
            return redirect('home')

    if request.method == 'POST' and 'call' in request.POST:
        call_form = CallForm(request.POST, prefix='call')
        if call_form.is_valid():
            return redirect('home')

    context = {'mail_form': mail_form,
               'call_form': call_form,
               'mail_form_errors': mail_form_errors,
               'call_form_errors': call_form_errors,
               }
    return render(request, 'silk/contacts.html', context)

templates/skv/ajax_test.html
{% extends 'skv/base.html' %}

{% load ajax_test %}

{% block title %} silkhouse.ru {% endblock %}


{% block body %}
    <div class="row">

        <div class="col-md-3">
            <button id="favorite" data-test="test_data" class="btn btn-primary" type="button">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
            </button>

{#            Template teg ajax_test#}
            {% btn %}
        </div>

        <div class="col-md-3">
            <div id="ajax_div">{{ category.likes }}</div>
        </div>

    </div>

    <script>

$('#favorite').click(function () {
    var test_data;
    test_data = $(this).attr("data-test");
{#    $.get('{% url "skv:ajax_test" %}', {test_data: 'test'}, function(data){#}
{#    http://127.0.0.1:8010/skv/ajax/test?test_data=test#}
    $.get('{% url "skv:ajax_test" %}', {test_data: test_data}, function (data) {
        $('#ajax_div').html(data);
{#        $('#favorite').hide();#}
    });
});

    </script>
{% endblock %}

templates/skv/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">#}
    <!-- Optional theme -->
    <link href="{% static "bootstrap/css/bootstrap-theme.min.css" %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">#}
    <!-- EXTRA -->
    <!-- Font awesome -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">#}
    <!-- Custom styles for this template -->
    <link href="{% static "css/skv.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/jquery-1.11.2.min.js" %}"></script>
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>#}
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>#}

    <!-- EXTRA JS -->


  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'skv' %}">SKV</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'skv:demo' %}">Demo</a></li>
            <li><a href="{% url 'skv:contacts' %}">Contacts & Messages</a></li>
            <li><a href="{% url 'skv:silk_index' %}">Old silk tamplate</a></li>
            <li><a href="{% url 'skv:spirit8' %}">Spirit8 tamplate</a></li>
          </ul>
        </div>
      </div>
    </nav>



    <div class="container">
        {% block body %}{% endblock %}
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted text-center"> Footer </p>
      </div>
    </footer>


  </body>
</html>

templates/skv/contacts.html
{% extends 'skv/base.html' %}

{% load crispy_forms_tags %}
{% load extra %}

{% block title %} Contacts {% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if messages %}
                <ul class="list-unstyled messages">
                    {% for message in messages %}
                        <li class="alert alert-{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="col-md-4"></div>
    </div>

    <div class="row">

        <div class="col-md-1">
        </div>

        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4> Задать вопрос </h4>
                </div>
                <div class="panel-body">
                    {% crispy mail_form %}
                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4> Обратный вызов </h4>
                </div>
                <div class="panel-body">
                    {% crispy call_form %}
                </div>
            </div>
        </div>

        <div class="col-md-1">
        </div>

    </div>
{% endblock %}

templates/skv/demo.html
{% extends 'skv/base.html' %}

{% load i18n %}

{% block title %} SKV Demo {% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center"> Demo </h1>

            <h2> Color Box </h2>

            <div class="foo" style="background-color:#13b4ff;"></div>
            <div class="foo" style="background-color:#ab3fdd;"></div>
            <div class="foo" style="background-color:#ae163e;"></div>

            <style>
                .foo {
                    float: left;
                    width: 20px;
                    height: 20px;
                    margin: 5px;
                    border-width: 1px;
                    border-style: solid;
                    border-color: rgba(0, 0, 0, .2);
                }
            </style>


            <h2> Passadvice </h2>
            <ins class="PassadviceWidget" data-user="1" data-action="1" style="display: inline-block; width: 1202px; height: 150px;"></ins>
            <script async src="http://dev.passadvice.me:8000/static/js/ext.js"></script>


        </div>
    </div>
    
{% endblock %}

templates/skv/index.html
{% extends 'skv/base.html' %}

{% block title %} SKV {% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <h1> Index </h1>
        </div>
    </div>

{% endblock %}