SilkDjango/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings


# TODO Добавить переменные из settings в templates
"""

"""


from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    # Core
    url(r'^$', 'core.views.landing', name='home'),
    url(r'^#tf-about$', 'core.views.landing', name='about'),
    url(r'^#tf-catalog$', 'core.views.landing', name='catalog'),
    url(r'^#tf-care$', 'core.views.landing', name='care'),
    url(r'^#tf-delivery$', 'core.views.landing', name='delivery'),
    url(r'^#tf-reviews$$', 'core.views.landing', name='reviews'),
    url(r'^#tf-contact$$', 'core.views.landing', name='contact'),

    url(r'^shop/', include('shop.urls', namespace='shop')),

    # SKV
    url(r'^skv/$', 'skv.views.index', name='skv'),
    url(r'^skv/', include('skv.urls', namespace='skv')),
    )

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

if settings.DEV:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

skv/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.generic import TemplateView



urlpatterns = patterns('skv.views',
    url(r'^/$', 'index', name='index'),
    url(r'^demo/$', 'demo', name='demo'),
    url(r'^contacts/$', 'contacts', name='contacts'),

    url(r'^spirit8/original$', TemplateView.as_view(template_name='demo/spirit8.html'), name='spirit8'),

    # AJAX
    url(r'^ajax/$', TemplateView.as_view(template_name='skv/ajax_test.html'), name='ajax'),
    url(r'^ajax/test$', 'ajax_test', name='ajax_test'),
    
    # Old silk demo
    url(r'^silk/$', 'silk_old_demo_index', name='silk_index'),
    url(r'^silk/about/$', 'silk_old_demo_about', name='silk_about'),
    url(r'^silk/care/$', 'silk_old_demo_care', name='silk_care'),
    url(r'^silk/delivery/$', 'silk_old_demo_delivery', name='silk_delivery'),
    url(r'^silk/contacts/$', 'silk_old_demo_contacts', name='silk_contacts'),
)

templates/silk/about.html
{% extends 'silk/base.html' %}

{% block title %} SKV {% endblock %}

{% block body %}
    <div class="col-md-3">
    </div>

    <div class="col-md-9">
        <h1>О платках</h1>

        <p>Шелковые платки из Индии!</p>

        <p>КАЖДЫЙ ПЛАТОК ЕДИНСТВЕННЫЙ!!!</p>

        <p>Ни один узор и цвет не повторяется!!!</p>

        <p>Silk House предлагает платки и палантины ручной работы из натурального бенаресского шёлка. Многоцветность,
            перламутровость, необычная технология изготовления делают каждый платок уникальным! Платки из нежнейшего
            шелка практически невесомы, приятны на ощупь, не электризуются.</p>

        <p>Шелковый платок сочетается с любой формой одежды: с вечерним платьем, офисным костюмом, повседневной одеждой.
            Шелковый платок также очень практичен. Он дарит прохладу летом и согревает зимой!</p>
    <br>
    <br>
    <br>
    <br>
    <br>

    </div>



{% endblock %}

templates/silk/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">#}
    <!-- Optional theme -->
    <link href="{% static "bootstrap/css/bootstrap-theme.min.css" %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">#}
    <!-- EXTRA -->
    <!-- Font awesome -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
{#    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">#}
    <!-- Custom styles for this template -->
    <link href="{% static "css/silk.css" %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container-fluid">
        {% block head %}{% include "silk/base_head.html" %}{% endblock %}
    </div>

    <div class="container">
        {% block body %}{% endblock %}
        <div class="row">
            <div class="col-md-12">
                <br>
            </div>
        </div>
    </div>




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/jquery-1.11.2.min.js" %}"></script>
{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>#}
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>#}
  </body>
    <footer>
    <div>
        {% block footer  %}{% include "silk/base_footer.html" %}{% endblock %}
    </div>
    </footer>
</html>

templates/silk/base_footer.html
<div class="row">

{#    Footer line#}
{#    <div class="row" style="background: #cfa73a;">#}
        <div class="col-md-12 text-center">
            <br>
        </div>
{#    </div>#}

{#    Footer line#}
{#    <div class="row">#}
        <div class="col-md-12 text-center">
            <br>
        </div>
{#    </div>#}

{#    Button row#}
    <div class="row">
        <div class="col-md-4 text-center">
        </div>

        <div class="col-md-4 text-center">
            <div class="row">

                {#                <ul class="nav nav-pills nav-justified">#}
                {#                    <li class=""><a href="#">VK</a></li>#}
                {#                    <li class=""><a href="#">Instagram</a></li>#}
                {#                </ul>#}
                <div class="btn-group btn-group-justified" role="group">
                    <a href="https://vk.com/silkhouse_ru" class="btn btn-block btn-social btn-vk"><span class="h4"><i
                            class="fa fa-vk"></i></span> VK</a>
                    <a href="https://instagram.com/silkhouse.ru" class="btn btn-block btn-social btn-instagram"><span
                            class="h4"><i class="fa fa-instagram"></i></span> Instagram</a>

                </div>


            </div>
        </div>

        <div class="col-md-4 text-center">
        </div>
    </div>

</div>

templates/silk/base_head.html
{% load extra %}

<div class="row">
    <div class="col-md-12 text-center" style="background: #e7b91b;">
        <br><span class='h1'><a href="{% url 'skv' %}"> SKV </a></span><br><br>
    </div>
</div>

<div class="row">
    <ul class="nav nav-pills nav-justified" style="background: #8f710e;">
        <li class="{% active_page request 'skv:silk_about' %}"><a href="{% url 'skv:silk_about' %}">О платках</a></li>
        <li class="{% active_page request 'skv:silk_delivery' %}"><a href="{% url 'skv:silk_delivery' %}">Оплата и Доставка</a></li>
        <li class="{% active_page request 'skv:silk_contacts' %}"><a href="{% url 'skv:silk_contacts' %}">Контакты</a></li>
        <li class="{% active_page request 'skv:silk_care' %}"><a href="{% url 'skv:silk_care' %}">Уход за платками</a></li>
    </ul>
</div>

templates/silk/care.html
{% extends 'silk/base.html' %}
{% load staticfiles %}

{% block title %} SKV {% endblock %}


{% block body %}
    <div class="row"><div class="col-md-12 text-center"><h1>Уход за шёлком</h1><hr></div></div>
{##}
{#    <div class="row">#}
{#        <div class="col-md-1"><img class="img-rounded" src="{% static "images/laundry/hand_wash.svg" %}" alt="Hand Wash"></div>#}
{#        <div class="col-md-6">#}
{#            <h3>Ручная стирка</h3>#}
{#            <p>Только ручная стрика. Максимальная температура воды 25 градусов. Не применять сухой стиральный порошок. Стирка только жидкими моющими средствами. Не рекомендуется предварительное «замачивание».</p>#}
{#        </div>#}
{#    </div>#}
{##}
{#    <div class="row">#}
{#        <div class="col-md-4">#}
{#            <div class="thumbnail">#}
{#                <img src="{% static "images/laundry/hand_wash.svg" %}" alt="Hand Wash">#}
{#                <div class="caption">#}
{#                    <h3>Ручная стирка</h3>#}
{#                    <p>Только ручная стрика. Максимальная температура воды 25 градусов.#}
{#                        Не применять сухой стиральный порошок. Стирка только жидкими моющими средствами.#}
{#                        Не рекомендуется предварительное «замачивание».</p>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

    <div class="row">
        <div class="col-md-4">
            <h2> Стираем шёлк </h2>
            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/hand_wash.svg" %}" alt="Hand Wash">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Ручная стирка</h4>
                    Только ручная стрика. Максимальная температура воды 25 градусов. Не применять сухой стиральный порошок. Стирка только жидкими моющими средствами. Не рекомендуется предварительное «замачивание».
                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/do_not_dryclean.svg" %}" alt="Do Not Dryclean">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Не подвергать химической чистке</h4>

                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/do_not_bleach.svg" %}" alt="Do Not Bleach">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Не применять отбеливающие средства</h4>

                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h2> Сушим шёлк </h2>
            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/drip_dry.svg" %}" alt="Drip Dry">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Дайте стечь воде</h4>
                    Для отжима платка сложить его несколько раз и сжать между ладонями, дать воде стечь.
                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/dry_flat.svg" %}" alt="Dry Flat">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Сушить расправленным</h4>
                    После отжима платок необходимо расправить и разложить на махровом полотенце.
                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/do_not_wring.svg" %}" alt="Do Not Wring">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Не скручивать</h4>

                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/do_not_tumble_dry.svg" %}" alt="Do Not Tumble Dry">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Не сушить в стиральной машине</h4>

                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/dry_in_shade.svg" %}" alt="Dry In Shade">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Не сушить на солнце</h4>

                </div>
            </div>
        </div>

        <div class="col-md-4">
            <h2> Гладим шёлк </h2>
            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/iron_low.svg" %}" alt="Iron Low">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Глажка при минимальной температуре</h4>

                </div>
            </div>

            <div class="media">
                <div class="media-left media-middle">
                    <img class="media-object" style="max-width: 36px;" src="{% static "images/laundry/do_not_steam.svg" %}" alt="Do Not Steam">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">Не отпаривать</h4>
                    Не использовать при глажке пар, так как он разрушает структуру волокна.
                </div>
            </div>
        </div>

    </div>




{#    <div class="col-md-2">#}
{#    </div>#}
{##}
{#    <div class="col-md-4">#}
{#        <div class="panel panel-default">#}
{#            <!-- Default panel contents -->#}
{#            <div class="panel-heading"><h3>Стирка</h3></div>#}
{#            <div class="panel-body">#}
{#                <p>...</p>#}
{#            </div>#}
{##}
{#            <!-- List group -->#}
{#            <ul class="list-group">#}
{#                <li class="list-group-item">Только ручная стрика.</li>#}
{#                <li class="list-group-item">Максимальная температура воды 30 градусов.</li>#}
{#                <li class="list-group-item">Не применять сухой стиральный порошок.</li>#}
{#                <li class="list-group-item">Стирка только жидкими моющими средствами (шампунь, ополаскиватель, жидкий стиральный порошок).</li>#}
{#                <li class="list-group-item">Не применять отбеливающие средства.</li>#}
{#                <li class="list-group-item">Не рекомендуется предварительное «замачивание».</li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{##}
{#    <div class="col-md-4">#}
{#        <div class="panel panel-default">#}
{#            <!-- Default panel contents -->#}
{#            <div class="panel-heading"><h3>После стирки</h3></div>#}
{#            <div class="panel-body">#}
{#                <p>...</p>#}
{#            </div>#}
{##}
{#            <!-- List group -->#}
{#            <ul class="list-group">#}
{#                <li class="list-group-item">Для отжима платка сложить его несколько раз и сжать между ладонями, дать воде стечь.</li>#}
{#                <li class="list-group-item">Запрещено скручивать платок.</li>#}
{#                <li class="list-group-item">После отжима платок необходимо расправить и разложить на махровом полотенце.</li>#}
{#                <li class="list-group-item">Глажка при минимальной температуре.</li>#}
{#                <li class="list-group-item">Не использовать при глажке пар, так как он разрушает структуру волокна.</li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}

{% endblock %}

templates/silk/contacts.html
{% extends 'silk/base.html' %}

{% load crispy_forms_tags %}


{% block title %} SKV {% endblock %}


{% block body %}

    <div class="row">
        <div class="col-md-6 text-center">
            <a href="tel:+79637699317"><h2><span class="glyphicon glyphicon-phone-alt"></span> +7 963 769-9317 </h2></a>
        </div>
        <div class="col-md-6 text-center">
            <a href="mailto:sales@silkhouse.ru"><h2><span class="glyphicon glyphicon-envelope"></span> sales@silkhouse.ru </h2></a>
        </div>
    </div>

    <div class="row"><div class="col-md-12"><hr></div></div>

    <div class="row">

        <div class="col-md-1">
        </div>

        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4> Задать вопрос </h4>
                </div>
                <div class="panel-body">
                    {% crispy mail_form %}
                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4> Обратный вызов </h4>
                </div>
                <div class="panel-body">
                    {% crispy call_form %}
                </div>
            </div>
        </div>

        <div class="col-md-1">
        </div>






{#        <div class="col-md-4">#}
{#            <form action="{% url 'skv:contacts' %}" method="post" class="form-horizontal">#}
{#                {% csrf_token %}#}
{#                {{ mail_form }}#}
{#                <input type="submit" value="Отправить"/>#}
{#            </form>#}
{#        </div>#}


{#        <div class="col-md-6">#}
{#             <form action="{% url 'skv:contacts' %}" method="post" class="form-horizontal">#}
{#                {% csrf_token %}#}
{##}
{#                {% for field in mail_form %}#}
{#                    <div class="form-group">#}
{#                        <label for="id_{{ field.name }}" class="col-sm-2 control-label">{{ field.label }}</label>#}
{##}
{#                        <div class="col-sm-10">#}
{#                            {{ field }}#}
{#                            {% if field.help_text %}<span id="{{ field.name }}" class="help-block">{{ field.help_text }}</span>{% endif %}#}
{#                        </div>#}
{#                    </div>#}
{#                {% endfor %}#}
{##}
{#                <div class="form-group">#}
{#                    <div class="col-sm-offset-2 col-sm-10">#}
{#                        <button type="submit" class="btn btn-default">Отправить</button>#}
{#                    </div>#}
{#                </div>#}
{#            </form>#}
{#        </div>#}

    </div>
{% endblock %}

templates/silk/delivery.html
{% extends 'silk/base.html' %}


{% block title %} SKV {% endblock %}

{% block body %}

    <div class="row">

        <div class="col-md-4"></div>

        <div class="col-md-4 well">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">
                        <span class="h3">
                            <i class="fa fa-info-circle"></i>
                        </span>
                        <span class="h3">Условия доставки</span>
                    </div>
                    <hr>
                </div>
                <div class="col-md-6">
                    <span class="h4">по Москве</span>
                    <p><b>100<i class="fa fa-rub"></i></b> Встреча с курьером в метро</p>
                    <p><b>200<i class="fa fa-rub"></i></b> Доставка в пределах МКАД</p>
                </div>
                <div class="col-md-6">
                    <span class="h4">по России</span>
                    <p><b>200<i class="fa fa-rub"></i></b> Отправка в регионы посылкой</p>
                    <p><b>300<i class="fa fa-rub"></i></b> Отправка наложным платежом</p>
                </div>
                <div class="col-md-12">
                    <hr>
                    <p><span class="h3"><i class="fa fa-clock-o"></i></span>
                        При заказе товара до 17:00 доставка производится на следующий день, за исключением воскресенья.
                        Доставка возможна с 9.00 до 21.00 по московскому времени.
                    </p>
                </div>

            </div>
        </div>

{#        <div class="col-md-4">#}
{#            <div class="panel panel-primary">#}
{#                <div class="panel-heading text-center">#}
{#                    <span class="h3"><i class="fa fa-info-circle"></i></span>#}
{#                    <span class="h3">Условия доставки</span>#}
{#                </div>#}
{##}
{#                <div class="panel-body">#}
{#                    <div class="row">#}
{#                        <div class="col-md-6">#}
{#                            <h4>по Москве:</h4>#}
{#                            <p><b>100<i class="fa fa-rub"></i></b> Встреча с курьером в метро</p>#}
{#                            <p><b>200<i class="fa fa-rub"></i></b> Доставка в пределах МКАД</p>#}
{#                        </div>#}
{#                        <div class="col-md-6">#}
{#                            <h4>по России:</h4>#}
{#                            <p><b>200<i class="fa fa-rub"></i></b> Отправка в регионы посылкой</p>#}
{#                            <p><b>300<i class="fa fa-rub"></i></b> Отправка наложным платежом</p>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div class="panel-footer">#}
{#                    <span class="h3"><i class="fa fa-clock-o"></i></span>#}
{#                    При заказе товара до 17:00 доставка производится на следующий день, за исключением воскресенья.#}
{#                    Доставка возможна с 9.00 до 21.00 по московскому времени.#}
{#                </div>#}
{#            </div>#}
{#        </div>#}

    </div>

{% endblock %}

templates/silk/index.html
{% extends 'silk/base.html' %}


{% block title %} silkhouse.ru {% endblock %}


{% block body %}
    <div class="row">
        <div class="col-md-3">

            {#      <p class="text-center h2">#}
            {#          <a href="#">Галерея</a>#}
            {#      </p>#}

            <br>

            <div class="btn-group btn-group-justified" role="group">
                <a class="btn btn-default" href="#"><p class="h4">Галерея</p></a>
            </div>
            <br>

            {#      <div class="btn-group-vertical" role="group">#}
            {#          <a class="btn btn-default" href="#">Галерея</a>#}
            {#      </div>#}

            <div class="list-group text-center h4">
                <a href="#" class="list-group-item">Мужские</a>
                <a href="#" class="list-group-item">Разноцветные</a>
                <a href="#" class="list-group-item">Палантины</a>
                <a href="#" class="list-group-item">Тонкий шёлк</a>
                <a href="#" class="list-group-item">Плотный шёлк</a>
            </div>
        </div>


        <div class="col-md-9">
            <div class="row">
                {% include 'silk/extra/thumbnails.html' %}
            </div>
        </div>
    </div>
{% endblock %}