SilkDjango/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings


# TODO Добавить переменные из settings в templates
"""

"""


from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    # Core
    url(r'^$', 'core.views.landing', name='home'),
    url(r'^#tf-about$', 'core.views.landing', name='about'),
    url(r'^#tf-catalog$', 'core.views.landing', name='catalog'),
    url(r'^#tf-care$', 'core.views.landing', name='care'),
    url(r'^#tf-delivery$', 'core.views.landing', name='delivery'),
    url(r'^#tf-reviews$$', 'core.views.landing', name='reviews'),
    url(r'^#tf-contact$$', 'core.views.landing', name='contact'),

    url(r'^shop/', include('shop.urls', namespace='shop')),

    # SKV
    url(r'^skv/$', 'skv.views.index', name='skv'),
    url(r'^skv/', include('skv.urls', namespace='skv')),
    )

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

if settings.DEV:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

shop/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('shop.views',
    url(r'^colors/$', 'colors_filter', name='colors'),

    url(r'^$', 'catalog', name='home'),
    url(r'^catalog/$', 'catalog', name='catalog'),
    url(r'^catalog/(?P<page>\d+)/$', 'catalog', name='catalog_page'),
    url(r'^catalog/color/$', 'colors_filter', name='catalog_color'),
    url(r'^filter/(?P<f_name>[-\w\d]+)/$', 'catalog', name='filter'),
    #
    url(r'^product/(?P<pk>\d+)/$', 'product', name='product'),
    url(r'^product/(?P<pk>\d+)/img/$', 'product_img', name='product_img'),
    #
    url(r'^basket/$', 'basket', name='basket'),
    # url(r'^product/(?P<pk>\d+)/edit/$', 'edit', name='product_edit'),
    #
    # Ajax
    #
    url(r'^ajax/menu/$', 'ajax_menu', name='ajax_menu'),
    # Favorite Button
    url(r'^ajax/favorite/(?P<pk>\d+)/$', 'ajax_favorite', name='favorite'),
    # Favorites ROW
    url(r'^ajax/favorites/$', 'ajax_favorites', name='ajax_favorites'),
    # Basket
    url(r'^basket/add/(?P<pk>\d+)/$', 'basket_add', name='basket_add'),
    url(r'^basket/remove/(?P<pk>\d+)/$', 'basket_remove', name='basket_remove'),
    url(r'^basket/drop/(?P<pk>\d+)/$', 'basket_drop', name='basket_drop'),


)

skv/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.generic import TemplateView



urlpatterns = patterns('skv.views',
    url(r'^/$', 'index', name='index'),
    url(r'^demo/$', 'demo', name='demo'),
    url(r'^contacts/$', 'contacts', name='contacts'),

    url(r'^spirit8/original$', TemplateView.as_view(template_name='demo/spirit8.html'), name='spirit8'),

    # AJAX
    url(r'^ajax/$', TemplateView.as_view(template_name='skv/ajax_test.html'), name='ajax'),
    url(r'^ajax/test$', 'ajax_test', name='ajax_test'),
    
    # Old silk demo
    url(r'^silk/$', 'silk_old_demo_index', name='silk_index'),
    url(r'^silk/about/$', 'silk_old_demo_about', name='silk_about'),
    url(r'^silk/care/$', 'silk_old_demo_care', name='silk_care'),
    url(r'^silk/delivery/$', 'silk_old_demo_delivery', name='silk_delivery'),
    url(r'^silk/contacts/$', 'silk_old_demo_contacts', name='silk_contacts'),
)

shop/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.templatetags.static import static
from django.conf import settings
from django.db.models import signals

from colors16.models import Colors
from core.utils import my_thumbnail

import os, shutil
from sorl.thumbnail import ImageField

# from django.forms.widgets import Select, SelectMultiple

# TODO Убрать методы с изображениями переписать
# TODO Перенести изображения в модель
# TODO Для каждого типа фото своё поле
# TODO
# TODO

class ScarfManager(models.Manager):
    # def get_queryset(self):
    def all(self):
        return super(ScarfManager, self).get_queryset()

    def update_all(self):
        q = self.all()
        for element in q:
            element.is_multicolor()
            element.save()

    def completed(self):
        q = self.all()
        # Check price
        q = q.filter(price__gt=0)
        # Check weight
        q = q.filter(weight__gt=0)
        # Check colors
        q = q.exclude(l_color__isnull=True)
        q = q.exclude(s_color__isnull=True)
        # Check photo
        q = q.exclude(img__isnull=True)
        return q

    def in_stock(self):
        q = self.completed()
        # В наличии больше одного
        return q.filter(count__gt=0)

    def on_sale(self):
        q = self.in_stock()
        # Не показываем скрытые
        return q.filter(hide__exact=False)

    def on_sale_male(self):
        q = self.on_sale()
        # Строгие цвета
        return q.filter(male__exact=True)

    def on_sale_bicolor(self):
        q = self.on_sale()
        return q.filter(multicolor__exact=False)

    def on_sale_multicolor(self):
        q = self.on_sale()
        return q.filter(multicolor__exact=True)

    def on_sale_lite(self):
        q = self.on_sale()
        # Легче чем 40 или равно
        return q.filter(weight__lte=40)

    def on_sale_hard(self):
        q = self.on_sale()
        # Тяжелее чем 40
        return q.filter(weight__gt=40)

    def sold_out(self):
        q = self.completed()
        # Проданные
        return q.filter(count__lte=0)


class Scarf(models.Model):
    img = ImageField(upload_to='scarfs/', null=True)
    title = models.CharField(u'Название', max_length=128, blank=True)
    count = models.PositiveSmallIntegerField(u'остаток', default=1)
    price = models.PositiveSmallIntegerField(u'цена', default=2000)
    weight = models.PositiveSmallIntegerField(u'Вес', default=25, )
    l_color = models.ForeignKey(Colors, related_name='l_color', null=True, blank=True)
    s_color = models.ManyToManyField(Colors, related_name='s_color', blank=True)
    multicolor = models.BooleanField(u'Цветной', default=False, )
    male = models.BooleanField(u'Строгие тона', default=False, )
    hide = models.BooleanField(u'Скрыть', default=False)
    objects = ScarfManager()

    def __str__(self):
        if self.title:
            return u'Шарф id.{} ({})'.format(self.id, self.title)
        else:
            return u'Шарф id.{}'.format(self.id)

    # Save filename as id.jpg
    # https://groups.google.com/forum/#!topic/django-users/PebyfpMzUyg
    def get_path(self, filename):
        save_name = os.path.join('scarfs', 'silkhouse_id_%s.jpg' % self.id)
        current_path = os.path.join(settings.MEDIA_ROOT, self.img.name)
        new_path = os.path.join(settings.MEDIA_ROOT, save_name)
        print(current_path)
        if os.path.exists(current_path):
            print('yo ho')
        shutil.move(current_path, new_path)
        return save_name

    def save(self):
        # if self.id is None:
        super(Scarf, self).save()
        self.img = self.get_path(self.img)
        super(Scarf, self).save()

    class Meta:
        ordering = ['id']
        verbose_name = u'Платок'
        verbose_name_plural = u'Платки'

    def get_absolute_url(self):
        return "/shop/product/%i/" % self.id


    # Update and signals methods

    def is_multicolor(self):
        if self.s_color.all().count() > 1:
            self.multicolor = True
        else:
            self.multicolor = False

def update_scarf(sender, instance, **kwargs):
    instance.is_multicolor()

signals.post_save.connect(update_scarf, sender=Scarf)

shop/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, render_to_response
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Scarf
from colors16.models import Colors

# Create your views here.

# TODO убрать сессии из контекста, возможно не стоит так как меню не обновляеться через ajax
# TODO favorite_row REWRITE
# TODO edit basket_row_btn, basket_product_btn
# TODO product_info_pannel REWRITE переместить favorite_btn в pannel_header изменить дизайн
# TODO ajax_basket_add проверять что есть в наличии


def catalog(request, f_name=None, page=1):
    tittle = False
    subtittle = False
    if f_name == 'male':
        tittle = "Мужские цвета"
        scarfs = Scarf.objects.on_sale_male()
    elif f_name == 'bicolor':
        scarfs = Scarf.objects.on_sale_bicolor()
        tittle = "Двухцветные платки"
        subtittle = "всего {} расцветки".format(scarfs.count())
    elif f_name == 'multicolor':
        scarfs = Scarf.objects.on_sale_multicolor()
        tittle = "Многоцветные платки"
        subtittle = "всего {} расцветки".format(scarfs.count())
    elif f_name == 'Легкий платок':
        tittle = "Мужские цвета"
        subtittle = "легче 40 грамм"
        scarfs = Scarf.objects.on_sale_lite()
    elif f_name == 'hard':
        tittle = "Плотный платок"
        subtittle = "тяжелее 40 грамм"
        scarfs = Scarf.objects.on_sale_hard()
    else:
        scarfs = Scarf.objects.on_sale()
        tittle = "Каталог"
        subtittle = "все {}".format(scarfs.count())
    #
    # https://docs.djangoproject.com/en/1.8/topics/pagination/
    #
    paginator = Paginator(scarfs, 36)
    try:
        scarfs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        scarfs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        scarfs = paginator.page(paginator.num_pages)
    #

    context = {
        'tittle': tittle,
        'subtittle': subtittle,
        'basket': request.session.get('basket'),
        #
        'scarfs': scarfs,
        'favorites': request.session.get('favorites'),
    }
    return render(request, 'shop/index.html', context)


def product(request, pk):
    scarf = get_object_or_404(Scarf, pk=int(pk))
    #
    basket = request.session.get('basket')
    #
    in_basket = False
    profile = request.session.get(pk)
    if profile:
        in_basket = profile.get('basket')
    #
    favorites = request.session.get('favorites')
    favorite = False
    if favorites:
        if scarf.id in favorites:
            favorite = True
    #
    request.session.modified = True
    context = {
        'scarf': scarf,
        'in_basket': in_basket,
        # Для кнопки
        'favorite': favorite,
        #
        'basket': request.session.get('basket'),
        'favorites': favorites,
    }
    # return render(request, 'shop/scarf_bg.html', context)
    return render(request, 'shop/scarf.html', context)


def product_img(request, pk):
    scarf = get_object_or_404(Scarf, pk=int(pk))
    context = {'scarf': scarf, }
    return render(request, 'shop/big_picture.html', context)


def basket(request):
    """ Вызывает страницу и вставляет basket_div

    rows:
        scarf_thumbnail
        in_basket + basket_btn
        price
        subsumm
    """
    basket = request.session.get('basket')

    scarfs = Scarf.objects.filter(pk__in=basket.keys())

    request.session.modified = True
    context = {
        'scarfs': scarfs,
        #
        'basket': basket,
        'favorites': request.session.get('favorites'),
    }
    return render(request, 'shop/basket.html', context)


def colors_filter(request):
    colors_list = []
    colors = Colors.objects.all()
    for color in colors:
        scarfs = Scarf.objects.completed()
        if scarfs.filter(l_color=color.id).count() > 0:
            colors_list.append(color.id)

    request.session.modified = True
    context = {
        'colors': colors,
        'colors_list': colors_list,
        #
        'basket': request.session.get('basket'),
        'favorites': request.session.get('favorites'),
        }
    return render(request, 'shop/colors.html', context)


# AJAX


def ajax_favorite(request, pk):
    """
    id в сессии это словарь для продукта или профиль
    Смотрим в профиле favorite
    Инвертируем полученое значение
    """
    # Если нет создаем ключ
    # Выставляем флаг в профиле
    favorite = True
    if not request.session.get(pk):
        request.session[pk] = {'favorite': favorite}
    else:
        profile = request.session[pk]
        # Если есть pk
        if profile.get('favorite'):
            # Удаляем ключ favorite если есть
            profile.pop('favorite')
            favorite = False
        else:
            profile['favorite'] = favorite
        request.session[pk] = profile

    # favorites
    scarfs = Scarf.objects.on_sale()
    favorites = []
    for s in scarfs:
        p = request.session.get(str(s.id))
        if p:
            f = p.get('favorite')
            if f:
                favorites.append(s.id)
    request.session['favorites'] = favorites

    request.session.modified = True
    context = {
        'scarf': Scarf.objects.get(pk=pk),
        'favorite': favorite,
        'favorites': favorites,
    }
    return render_to_response('shop/include/favorite_btn.html', context)

# Возвращает basket_div


def ajax_basket(request):
    #
    request.session.modified = True
    context = {
        # 'scarf': Scarf.objects.get(pk=pk),
        # 'in_basket': in_basket,
        # 'basket': basket,
        # 'basket': basket,
        #
        'favorites': request.session.get('favorites'),
    }
    return render_to_response('shop/include/basket_btn_product.html', context)

# Возвращает basket_btn_product

def basket_add(request, pk):
    in_basket = False
    # Если профиля небыло
    if not request.session.get(pk):
        request.session[pk] = {'basket': 1}
        in_basket = 1
    else:
        profile = request.session[pk]
        # Если есть pk
        if profile.get('basket'):
            # Удаляем ключ favorite если есть
            basket = profile.pop('basket')
            profile['basket'] = basket + 1
        else:
            profile['basket'] = 1
        in_basket = profile['basket']
        request.session[pk] = profile
    # basket
    scarfs = Scarf.objects.on_sale()
    basket = {}
    for s in scarfs:
        p = request.session.get(str(s.id))
        if p:
            b = p.get('basket')
            if b:
                basket[s.id] = b
    request.session['basket'] = basket
    #
    request.session.modified = True
    context = {
        'scarf': Scarf.objects.get(pk=pk),
        'in_basket': in_basket,
        'basket': basket,
        # 'basket': basket,
        #
        'favorites': request.session.get('favorites'),
    }
    return render_to_response('shop/include/basket_btn_product.html', context)


def basket_remove(request, pk):
    in_basket = False
    # Если есть профиль
    if request.session.get(pk):
        profile = request.session[pk]
        # Если есть pk
        if profile.get('basket'):
            # Удаляем ключ favorite если есть
            basket = profile.pop('basket')
            if basket > 1:
                profile['basket'] = basket - 1
                in_basket = profile['basket']
        request.session[pk] = profile
    # basket
    scarfs = Scarf.objects.on_sale()
    basket = {}
    for s in scarfs:
        p = request.session.get(str(s.id))
        if p:
            b = p.get('basket')
            if b:
                basket[s.id] = b
    request.session['basket'] = basket
    #
    request.session.modified = True
    context = {
        'scarf': Scarf.objects.get(pk=pk),
        'in_basket': in_basket,
        'basket': basket,
        #
        'favorites': request.session.get('favorites'),
    }
    return render_to_response('shop/include/basket_btn_product.html', context)


def basket_drop(request, pk):
    in_basket = False
    # Если есть профиль
    if request.session.get(pk):
        profile = request.session[pk]
        # Если есть pk
        if profile.get('basket'):
            # Удаляем ключ basket если есть
            profile.pop('basket')
        request.session[pk] = profile
    # basket
    scarfs = Scarf.objects.on_sale()
    basket = {}
    for s in scarfs:
        p = request.session.get(str(s.id))
        if p:
            b = p.get('basket')
            if b:
                basket[s.id] = b
    request.session['basket'] = basket
    #
    request.session.modified = True
    context = {
        'scarf': Scarf.objects.get(pk=pk),
        'in_basket': in_basket,
        'basket': basket,
        #
        'favorites': request.session.get('favorites'),
    }
    return render_to_response('shop/include/basket_btn_product.html', context)

# AJAX session only


def ajax_menu(request):
    context = {
        #
        'basket': request.session.get('basket'),
        'favorites': request.session.get('favorites'),
        }
    return render_to_response('shop/include/base_menu.html', context)


def ajax_favorites(request):
    context = {
        #
        'basket': request.session.get('basket'),
        'favorites': request.session.get('favorites'),
        }
    return render_to_response('shop/include/favorite_div.html', context)

templates/shop/include/base_footer.html
    <nav id="footer">
        <div class="container">
            <div class="pull-left nav">
{#                <p>ALL RIGHTS RESERVED. COPYRIGHT © 2014. Designed by <a href="https://dribbble.com/shots/1817781--FREEBIE-Spirit8-Digital-agency-one-page-template" target="_blank">Robert Berki</a> and Coded by <a href="https://dribbble.com/jennpereira" target="_blank">Jenn Pereira</a></p>#}
                <p> +7(XXX)XXX-XX-XX  <a href="http://silkhouse.ru">silkhouse.ru</a></p>
            </div>
            <div class="pull-right nav">
                <ul class="footer-social">
                    <li><a href="https://vk.com/silkhouse_ru"><i class="fa fa-vk"></i></a></li>
                    <li><a href="https://instagram.com/silkhouse.ru/"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>

templates/shop/include/base_head.html
{% load scarf %}
<nav id="tf-menu" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">silkhouse.ru</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul id="menu_div" class="nav navbar-nav navbar-right">

                {% include 'shop/include/base_menu.html' %}

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

templates/shop/include/base_menu.html
{#                # Class Active#}
{#                <li class="{% active_page request 'skv:silk_delivery' %}"><a href="{% url 'skv:silk_delivery' %}">Оплата и Доставка</a></li>#}

{% if landing %}
    {#            <li><a href="#tf-home" ><span class="glyphicon glyphicon-home"></span></a></li>#}
    <li><a href="#tf-about" class="page-scroll">О платках</a></li>
    <li><a href="#tf-market" class="page-scroll">Каталог</a></li>
    <li><a href="#tf-care" class="page-scroll">Уход</a></li>
    <li><a href="#tf-delivery" class="page-scroll">Доставка и Оплата</a></li>
    <li><a href="#tf-reviews" class="page-scroll">Отзывы</a></li>
    <li><a href="#tf-contact" class="page-scroll">Контакты</a></li>
{% else %}
    {#            <li><a href="#tf-home" ><span class="glyphicon glyphicon-home"></span></a></li>#}
    <li><a href="{% url 'about' %}">О платках</a></li>
    {#                    <li class="active"><a href="{% url 'shop:home' %}">Каталог</a></li>#}
    <li class="active"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        Каталог <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'shop:filter' 'bicolor' %}"><i>Двухцветные</i></a></li>
        <li><a href="{% url 'shop:filter' 'multicolor' %}"><i>Многоцветные</i></a></li>
{#        <li><a href="{% url 'shop:filter' 'lite' %}">Тонкий шёлк</a></li>#}
{#        <li><a href="{% url 'shop:filter' 'hard' %}">Плотный шёлк</a></li>#}
        <li role="separator" class="divider"></li>
        <li class="text-center"><a href="{% url 'shop:catalog_color' %}">По цвету</a></li>
        <li role="separator" class="divider"></li>
        <li class="text-center"><a href="{% url 'shop:home' %}"><strong>Все</strong></a></li>
    </ul>
    </li>
    <li><a href="{% url 'care' %}">Уход</a></li>
    <li><a href="{% url 'delivery' %}">Доставка и Оплата</a></li>
    <li><a href="{% url 'reviews' %}">Отзывы</a></li>
    <li><a href="{% url 'contact' %}">Контакты</a></li>
{% endif %}

{% if favorites %}
    <li>
        {% if landing %}
            <a href="{% url 'shop:home' %}">
                <span class="glyphicon glyphicon-star"></span>({{ favorites|wordcount }})
            </a>
        {% else %}
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#favorite_row"
               href="#collapseFavoriteRow" aria-expanded="false" aria-controls="collapseFavoriteRow" style="color:gold">
                <span class="glyphicon glyphicon-star"></span>({{ favorites|wordcount }})
            </a>
        {% endif %}
    </li>
{% endif %}

{% if basket %}
    <li class="dropdown">
        {% if landing %}
            <a href="{% url 'shop:home' %}">
                <span class="glyphicon glyphicon-shopping-cart"></span>
            </a>
        {% else %}
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" style="color:gold"
               aria-expanded="false">
                <span class="glyphicon glyphicon-shopping-cart">({{ basket.keys|wordcount }})
                <span class="caret"></span></a>
            <ul class="dropdown-menu">
            {% for key, value in basket.items %}
                <li><a href="{% url 'shop:product' key %}"> Платок id.{{ key }} &nbsp;&nbsp;&nbsp; ({{ value }} шт.)</a></li>
            {% endfor %}
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'shop:basket' %}"> <strong>Оформить заказ</strong> </a></li>
            </ul>
            </li>
        {% endif %}
{% endif %}

templates/shop/include/basket_btn_product.html
{% if in_basket %}
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button id="basket_btn_remove" type="button" class="btn btn-warning">
               <span class="h2"><i class="fa fa-minus-circle"></i></span>
            </button>
        </div>
        <div class="btn-group" role="group">
            <a type="button" class="btn btn-warning" href="{% url 'shop:basket' %}">
                <span class="h2"><i class="fa fa-shopping-cart"> ({{ in_basket }})</i></span>
            </a>
        </div>
        <div class="btn-group" role="group">
            <button id="basket_btn_add" type="button" class="btn btn-warning {% if scarf.count <= in_basket %} disabled {% endif %}">
                <span class="h2"><i class="fa fa-plus-circle"></i></span>
            </button>
        </div>

    </div>
{% else %}
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button id="basket_btn_add" type="button" class="btn btn-warning">
                <span class="h1"><i class="fa fa-cart-plus"></i> </span><span class="h3"> в корзину</span>
            </button>
        </div>
    </div>
{% endif %}

<script>
    $('#basket_btn_add').click(function () {
        $.ajaxSetup({async: false});
        $.get('{% url "shop:basket_add" scarf.id %}', function (data) {
            $('#basket_btn_div').html(data);
        });
        $.get('{% url "shop:ajax_menu" %}', function (data) {
            $('#menu_div').html(data);
        });
    });

    $('#basket_btn_remove').click(function () {
        $.ajaxSetup({async: false});
        $.get('{% url "shop:basket_remove" scarf.id %}', function (data) {
            $('#basket_btn_div').html(data);
        });
        $.get('{% url "shop:ajax_menu" %}', function (data) {
            $('#menu_div').html(data);
        });
    });

    $('#basket_btn_drop').click(function () {
        $.ajaxSetup({async: false});
        $.get('{% url "shop:basket_drop" scarf.id %}', function (data) {
            $('#basket_btn_div').html(data);
        });
        $.get('{% url "shop:ajax_menu" %}', function (data) {
            $('#menu_div').html(data);
        });
    });

    {#    $(function () {#}
    {#        $('[data-toggle="tooltip"]').tooltip()#}
    {#    })#}
</script>

templates/shop/include/catalog_pagination.html
<div class="text-center"
  <nav>
    <ul class="pagination">

{#        {% if scarfs.has_previous %}#}
{#            <li>#}
{#                <a href="{% url 'shop:catalog_page' scarfs.previous_page_number %}" aria-label="Previous">#}
{#                    <span aria-hidden="true">&laquo;</span>#}
{#                </a>#}
{#            </li>#}
{#        {% endif %}#}

        {% for page in  scarfs.paginator.page_range %}
            {% if page == scarfs.number %}
                <li class="active"><a href="{% url 'shop:catalog_page' page %}">{{ page }}</a></li>
            {% else %}
                <li><a href="{% url 'shop:catalog_page' page %}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}

{#        {% if scarfs.has_next %}#}
{#            <li>#}
{#                <a href="{% url 'shop:catalog_page' scarfs.next_page_number %}" aria-label="Next">#}
{#                    <span aria-hidden="true">&raquo;</span>#}
{#                </a>#}
{#            </li>#}
{#        {% endif %}#}

    </ul>
  </nav>
</div>

templates/shop/include/favorite_btn.html
<span id="favorite" data-pk="{ {favorite }}" class="h1" style="color: #FCAC45;">
    {% if favorite %}
        <i class="fa fa-star"
           data-toggle="tooltip" data-placement="right" title="В избранном "></i>
    {% else %}
        <i class="fa fa-star-o"
           data-toggle="tooltip" data-placement="right" title="Добавить в избранные"></i>
    {% endif %}
</span>

<script>
    $('#favorite').click(function () {
        $.ajaxSetup({async: false});
        $.get('{% url "shop:favorite" scarf.id %}', function (data) {
            $('#favorite_div').html(data);
        });
        $.get('{% url "shop:ajax_menu" %}', function (data) {
            $('#menu_div').html(data);
        });
        $.get('{% url "shop:ajax_favorites" %}', function (data) {
            $('#favorites_div').html(data);
        });
    });

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

templates/shop/include/product_info_panel_wrapper.html
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <div class="panel panel-warning">
        <div class="panel-heading" role="tab" id="headingInfo">
            <div class="panel-title">

                <span class="text-left">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseInfo" aria-expanded="true"
                    aria-controls="collapseInfo">
                        <span class="h1"> <i class="fa fa-tags"> id.{{ scarf.id }}</i></span>
                    </a>
                </span>

                <span id="favorite_div" class="pull-right">
                    {% include 'shop/include/favorite_btn.html' %}
                </span>

            </div>
        </div>

        <div id="collapseInfo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingInfo">
            {% include 'shop/include/product_info_panel.html' %}
        </div>

{#        <div class="panel-footer">Panel footer</div>#}

    </div>
</div>